/**
 * 제너럴 리딩 75세트 — (질문×스프레드)별 고유 직접 답변 + 추가 통찰
 * 각 75개 조합마다 서로 다른 문구. 재탕 없음.
 * - DIRECT_ANSWER: 75 × { ko, en, ja } 한 줄
 * - ADDITIONAL_INSIGHTS: 75 × { ko, en, ja } 2줄 배열
 */

const Q = [
  'love_1', 'love_2', 'love_3',
  'career_1', 'career_2', 'career_3',
  'money_1', 'money_2', 'money_3',
  'relationship_1', 'relationship_2', 'relationship_3',
  'fortune_1', 'fortune_2', 'fortune_3',
];
const S = ['time_3', 'solution_3', 'relationship_5', 'cross_4', 'insight_3'];

/** 75개 고유 직접 답변 — (questionId_spreadId) → { ko, en, ja } */
const DIRECT_ANSWER_RAW = {
  love_1_time_3: { ko: '과거부터 지금까지 그쪽은 말하지 못한 후회가 남아 있었을 수 있고, 앞으로는 당신이 먼저 연락하지 않으면 그쪽도 쉽게 다가오지 않을 가능성이 큽니다.', en: 'From past to now they may have had unspoken regret; going forward, if you don\'t reach out first, they are unlikely to make the first move easily.', ja: '過去から今まで言えなかった後悔が残っていたかも。これからはあなたから連絡しなければ相手も簡単には動かない可能性が高いです。' },
  love_1_solution_3: { ko: '전 애인이 나를 어떻게 생각하는지 궁금하지만 직접 묻기 어렵고, 다시 사귀기보다는 "그 사람이 나를 제대로 알아봐줬으면 좋겠다"는 마음이 더 클 수 있어요.', en: 'You may wonder what they think of you but find it hard to ask; the wish to feel acknowledged can be stronger than to get back together.', ja: '「あの人は私をどう思っているか」気になるが聞きづらい。復縁より認められたい気持ちが強いかも。' },
  love_1_relationship_5: { ko: '그 사람은 과거 관계를 완전히 정리하지 못한 상태일 수 있어요. 당신이 먼저 연락하지 않으면 그쪽도 쉽게 다가오지 않을 가능성이 큽니다.', en: 'They may not have fully closed the chapter; if you don\'t reach out first, they are unlikely to make the first move easily.', ja: 'その人は過去の関係を完全に区切れていないかも。あなたから連絡しなければ相手も簡単には動かない可能性が高いです。' },
  love_1_cross_4: { ko: '과거 관계가 완전히 정리되지 않았거나 못 다한 말이 있어서 마음이 남아 있을 수 있고, 시간이 지나면 감정이 옅어지거나 다시 이야기하고 싶어질 수 있어요.', en: 'The past may not be fully closed or there may be things left unsaid; over time their feelings may fade or they may want to talk again.', ja: '過去の関係が区切れていなかったり言えなかったことが残っているかも。時間が経てば感情が薄まるか、また話したくなるか。' },
  love_1_insight_3: { ko: '밖으로는 쿨해 보여도 마음까지 정리됐다고 단정하기 어렵고, 당신이 먼저 연락하지 않는다면 그쪽도 쉽게 다가오지 않을 가능성이 큽니다.', en: 'They may seem cool but it\'s hard to say their heart is fully closed; if you don\'t reach out first, they\'re unlikely to move easily.', ja: '表ではクールに見えても心まで整理されたとは言い切れず、あなたから連絡しなければ相手も簡単には動かない可能性が高いです。' },

  love_2_time_3: { ko: '두 사람의 만남에는 필연이 섞여 있고, 지금은 성장 단계라 하루하루 대화와 경험을 쌓는 쪽이 유리해요.', en: 'Your meeting had a sense of fate; you\'re in a growth phase, so building conversation and experience day by day is favorable.', ja: '二人の出会いには必然が。今は成長段階なので日々の会話と経験を積む方が有利です。' },
  love_2_solution_3: { ko: '"진짜 맞는 사람일까" 불안해도 관계를 소중히 하고 있다는 신호이고, 단기로 결과를 재촉하기보다 함께 걸어가며 만드는 쪽이 유리해요.', en: 'Anxiety about "is this the one?" can be a sign you care; building the relationship step by step is more favorable than rushing for a result.', ja: '「本当に合う人？」と不安でも関係を大切にしている証。短期で結果を急ぐより一緒に歩みながら作る方が有利です。' },
  love_2_relationship_5: { ko: '그 사람은 당신을 소중히 생각하고 관계를 깊게 하고 싶어 할 수 있어요. 서로 노력하면 깊어질 가능성이 있어요.', en: 'They may value you and want to deepen the relationship; it can deepen if you both invest.', ja: 'その人はあなたを大切に思い、関係を深めたいかも。二人が努めれば深まる可能性が。' },
  love_2_cross_4: { ko: '관계는 아직 성장 단계이고, 만남에 필연이 섞여 있어요. 결과를 재촉하기보다 대화와 경험을 쌓는 쪽이 유리합니다.', en: 'The relationship is still growing and your meeting had a sense of fate; building conversation and experience is more favorable than rushing.', ja: '関係はまだ成長段階で、出会いに必然が。結果を急ぐより会話と経験を積む方が有利です。' },
  love_2_insight_3: { ko: '만남에 필연이 섞여 있다는 느낌이 있고, 진짜 인연은 함께 걸어가며 만들어지는 경우가 많아요.', en: 'There\'s a sense of fate in your meeting; true match is often made by walking together.', ja: '出会いに必然が混ざっている感覚が。本当の運命の人は一緒に歩みながら作られることが多いです。' },

  love_3_time_3: { ko: '지금까지 끌림과 망설임이 있었고, 지금은 전환점이라 몇 달 안에 관계 방향이 더 분명해질 가능성이 큽니다.', en: 'There has been both attraction and hesitation; you\'re at a turning point and the direction may become clearer within a few months.', ja: 'これまで惹かれつつ迷いもあった。今は転換点で、数ヶ月以内に関係の方向性がはっきりする可能性が高いです。' },
  love_3_solution_3: { ko: '"이 관계를 어떻게 할지" 불명확할 수 있어요. 결말을 급하게 정하기보다 지금 할 수 있는 말과 행동을 하는 쪽이 후회가 적어요.', en: 'You may feel unclear about the relationship; doing what you can say and do now tends to leave fewer regrets than forcing an ending.', ja: '「この関係をどうするか」不明確かも。結末を急がず、今できる言葉と行動をすることが後悔を減らします。' },
  love_3_relationship_5: { ko: '두 사람 모두 관계를 소중히 생각하지만 어디까지 갈지 확신이 없을 수 있고, 솔직히 말하고 들으면 몇 달 안에 방향이 분명해질 수 있어요.', en: 'You both may value the relationship but lack certainty about how far it will go; speaking and listening honestly can clarify direction within months.', ja: '二人とも関係を大切にしているがどこまで行くか確信がないかも。正直に話し聞けば数ヶ月で方向がはっきりすることが。' },
  love_3_cross_4: { ko: '지금은 전환점이고 상대 반응에 일희일비하지 말고 자신이 원하는 방향을 먼저 정리하는 것이 좋아요.', en: 'You\'re at a turning point; clarify what you want first rather than swinging with every reaction.', ja: '今は転換点。相手の反応に一喜一憂せず、自分が望む方向を先に整理するのがおすすめです。' },
  love_3_insight_3: { ko: '겉으로는 잘 지내는 사이처럼 보여도 "이 관계를 어떻게 할지" 고민이 있을 수 있고, 할 수 있는 말과 행동을 하는 쪽이 후회가 적어요.', en: 'On the surface it may look like you get along, but there may be worry about the relationship; doing what you can say and do tends to leave fewer regrets.', ja: '表では仲良くしているように見えても「この関係をどうするか」の悩みがあるかも。できる言葉と行動をすることが後悔を減らします。' },

  career_1_time_3: { ko: '과거에 불만이 쌓였고 지금은 방향을 정리하는 신호이며, 반년~1년 안에 기회가 보일 수 있어요.', en: 'Frustration built in the past; now is a signal to clarify direction, and opportunities may appear within six months to a year.', ja: '過去に不満が溜まり、今は方向を整理するサイン。半年〜1年以内にチャンスが見えるかも。' },
  career_1_solution_3: { ko: '어떤 방향으로 가고 싶은지 먼저 정리하는 것이 유리하고, 준비가 되어 있을 때 타이밍이 열리는 경우가 많아요.', en: 'Clarifying which direction you want first is favorable; timing often opens when you\'re ready.', ja: 'どの方向へ行きたいか先に整理するのが有利。準備が整った時にタイミングが開くことが多いです。' },
  career_1_relationship_5: { ko: '성장 욕구와 현실 사이 간격을 느끼고 있을 수 있어요. 준비가 되어 있을 때 반년~1년 안에 한두 번 기회가 보일 가능성이 있어요.', en: 'You may feel the gap between your desire to grow and reality; when you\'re ready, one or two opportunities may appear within six months to a year.', ja: '成長欲求と現実のギャップを感じているかも。準備が整えば半年〜1年以内に一二回チャンスが見える可能性が。' },
  career_1_cross_4: { ko: '지금은 방향을 먼저 정리하고 실력·인맥·정보를 쌓아 두면 반년~1년 안에 기회가 보이는 흐름이에요.', en: 'Clarifying direction and building skills, network, and information now can lead to opportunities within six months to a year.', ja: '今は方向を先に整理し、実力・人脈・情報を積んでおけば半年〜1年以内にチャンスが見える流れです。' },
  career_1_insight_3: { ko: '겉으로 괜찮아 보여도 "언제쯤 기회가 올까" 생각이 있을 수 있고, 그때를 위해 지금 할 수 있는 준비를 해 두세요.', en: 'You may seem fine but wonder when an opportunity will come; prepare now for that time.', ja: '表では大丈夫に見えても「いつ頃チャンスが来るか」と思っているかも。その時のために今できる準備をしておいて。' },

  career_2_time_3: { ko: '과거에 쓸 만한 사람으로 보이기 시작했고, 지금은 결과를 보여주는 한두 번의 일이 관계를 바꿀 수 있는 시기예요.', en: 'They started to see you as useful in the past; now one or two concrete results can change the relationship.', ja: '過去に使える人と見られ始め、今は結果を見せる仕事が一二回あると関係が変わる時期です。' },
  career_2_solution_3: { ko: '아직 완전히 믿고 맡기기에는 한 단계 부족하다고 느낄 수 있어요. 말만 하지 말고 결과를 보여주는 일이 관계를 바꿔요.', en: 'They may feel one step short of fully trusting you with more; concrete results can change the relationship.', ja: '完全に任せるにはあと一歩と感じているかも。言葉より結果を見せる仕事が関係を変えます。' },
  career_2_relationship_5: { ko: '상사는 당신을 키워볼 만한 사람으로 보지만 한 단계 부족하다고 느낄 수 있어요. 결과를 보여주는 한두 번의 일이 관계를 바꿀 수 있어요.', en: 'Your boss may see you as worth developing but feel one step short; one or two concrete results can change the relationship.', ja: '上司はあなたを育てる価値がある人と見ているが、あと一歩と感じているかも。結果を見せる仕事が一二回あると関係が変わります。' },
  career_2_cross_4: { ko: '팀에서 꼭 필요한 한 명이지만 "이 사람 없이는 안 된다" 수준까지는 아닐 수 있어요. 꾸준히 신뢰를 쌓으면 몇 달 안에 위치가 올라갈 수 있어요.', en: 'You\'re one of the necessary people but not yet indispensable; building trust steadily can raise your standing within months.', ja: 'チームで必要な一人だが「この人がいないと困る」レベルまではいかないかも。コツコツ信頼を積めば数ヶ月でポジションが上がるかも。' },
  career_2_insight_3: { ko: '상사·동료는 아직 "한 단계 더 보여주면 믿고 맡기겠다"는 단계일 수 있어요. 특정 분야에서 강점을 보이거나 위기에서 한 번 잘 해내면 위치가 올라갈 수 있어요.', en: 'Your boss and colleagues may still be at "show us one more step"; showing strength in one area or performing well in a pinch can raise your standing.', ja: '上司・同僚はまだ「あと一歩見せてくれたら任せたい」段階かも。特定分野で強みを見せるか、ピンチで一度結果を出せばポジションが上がるかも。' },

  career_3_time_3: { ko: '큰 불행은 없지만 눈에 띄는 행운이 쏟아지는 단계는 아니에요. 꾸준히 일하면 조금씩 인정받고 작은 기회가 생기는 흐름이에요.', en: 'No major misfortune but not a phase of obvious windfalls; steady work tends to bring gradual recognition and small opportunities.', ja: '大きな不幸はないが、目立つ幸運が降り注ぐ段階ではない。コツコツ仕事をすれば少しずつ認められ、小さなチャンスが生まれる流れです。' },
  career_3_solution_3: { ko: '대박을 노리기보다 할 수 있는 일을 착실히 하는 것이 운을 키우고, 동료·상사 중 좋은 영향을 주는 사람이 있어요.', en: 'Doing what you can reliably helps build luck more than chasing a big break; there are people who have a positive influence on you.', ja: '大当たりを狙うよりできることを着実にすることが運を育てる。同僚・上司の中に良い影響を与える人がいます。' },
  career_3_relationship_5: { ko: '일운은 "꾸준히 인정받고 작은 기회가 생기는" 흐름에 가깝고, 몇 달~1년 사이에 "이번 일 잘됐다" 같은 경험이 한두 번 생길 가능성이 있어요.', en: 'Your work luck is closer to gradual recognition and small opportunities; within months to a year you may have one or two "that went well" experiences.', ja: '仕事運は「少しずつ認められ、小さなチャンスが生まれる」流れに近い。数ヶ月〜1年以内に「この仕事うまくいった」という経験が一二回ある可能性が。' },
  career_3_cross_4: { ko: '지금은 꾸준히 일하면 조금씩 인정받고 작은 기회가 생기는 흐름이고, 그때를 위해 지금 할 수 있는 준비를 해 두세요.', en: 'Now steady work tends to bring gradual recognition and small opportunities; prepare now for that time.', ja: '今はコツコツ仕事をすれば少しずつ認められ、小さなチャンスが生まれる流れ。その時のために今できる準備をしておいて。' },
  career_3_insight_3: { ko: '겉으로는 평범한 일상처럼 보여도 꾸준히 일하면 인정받고 작은 기회가 생기고, 몇 달~1년 사이에 "이번 일 잘됐다" 같은 경험이 생길 수 있어요.', en: 'On the surface it may look like ordinary routine, but steady work brings recognition and small opportunities; within months to a year you may have a "that went well" experience.', ja: '表では平凡な日常に見えても、コツコツ仕事をすれば認められ小さなチャンスが。数ヶ月〜1年以内に「この仕事うまくいった」という経験があるかも。' },

  money_1_time_3: { ko: '지금은 꾸준한 소득이나 작은 보너스가 이어지는 흐름일 수 있고, 반년~1년 안에 수입이 늘거나 예상치 못한 소득이 생길 가능성이 있어요.', en: 'You may see steady income or small bonuses now; within six months to a year income may increase or unexpected money may appear.', ja: '今は安定した収入や小さなボーナスが続く流れかも。半年〜1年以内に収入が増えたり予想外の収入がある可能性が。' },
  money_1_solution_3: { ko: '불필요한 지출을 줄이고 저축·정리를 해 두면 나중에 "돈이 필요할 때" 수월해지고, 돈이 들어오기 전에 쓰는 습관을 줄이세요.', en: 'Cutting unnecessary spending and saving or organizing now will make "when you need money" easier later; reduce the habit of spending before money arrives.', ja: '無駄な支出を減らし貯金・整理をしておくと、あとで「お金が必要な時」が楽に。お金が入る前に使う癖を減らして。' },
  money_1_relationship_5: { ko: '지금은 꾸준한 소득 흐름일 수 있고, 정보를 모으고 준비해 둔 자격이나 실력이 있으면 반년~1년 안에 그때 발휘될 수 있어요.', en: 'You may see steady income now; if you\'ve gathered information and have skills or credentials ready, they can pay off within six months to a year.', ja: '今は安定した収入の流れかも。情報を集め、資格や実力の準備があれば半年〜1年以内にその時に活きるかも。' },
  money_1_cross_4: { ko: '지금은 꾸준한 소득이나 작은 보너스 흐름일 수 있어요. 돈이 들어오기 전에 쓰는 습관을 줄이고 들어온 돈의 일부는 따로 모아 두세요.', en: 'You may see steady income or small bonuses now; reduce spending before money arrives and set aside part of what comes in.', ja: '今は安定した収入や小さなボーナスの流れかも。お金が入る前に使う癖を減らし、入ったお金の一部は別に貯めて。' },
  money_1_insight_3: { ko: '겉으로는 큰 수입이 한 번에 들어오는 단계는 아닐 수 있어요. "나중에"라고 미루지 말고 이번 달부터 작은 금액이라도 저축을 시작하세요.', en: 'You may not be in a phase of one big windfall; don\'t put it off "for later"—start saving even a small amount this month.', ja: '表では大きな収入が一気に入る段階ではないかも。「あとで」と延ばさず、今月から少額でも貯金を始めて。' },

  money_2_time_3: { ko: '과거에 "뭔가 해야 할 것 같은데 뭘 해야 할지 모르겠다"는 느낌이 있었을 수 있어요. 무리한 투자보다 안정 저축+소액 분산이 당신에게 맞아요.', en: 'You may have felt "I should do something but don\'t know what"; stable saving and small diversified investment tend to fit you better than aggressive investing.', ja: '過去に「何かした方がいいけど何をすればいいか分からない」感覚があったかも。無理な投資より安定貯金＋少額分散があなたに合います。' },
  money_2_solution_3: { ko: '방향이 흐릿할 수 있어요. 유행하는 코인이나 "반드시 오른다"는 말에 쉽게 끌려가지 말고, 매달 고정 금액을 저축·투자에 쓰는 습관을 들이세요.', en: 'Direction may feel unclear; don\'t be pulled in by hype; build a habit of putting a fixed amount into saving/investment each month.', ja: '方向がぼやけているかも。流行に簡単に乗らず、毎月一定額を貯金・投資に回す習慣をつけて。' },
  money_2_relationship_5: { ko: '지금은 "뭔가 해야 할 것 같은데 뭘 해야 할지 모르겠다"는 방향이 흐릿한 상태일 수 있어요. 원금을 지키는 것을 최우선으로 하세요.', en: 'You may feel direction is unclear; protect principal first.', ja: '今は「何かした方がいいけど何をすればいいか分からない」と方向がぼやけているかも。元本を守ることを最優先に。' },
  money_2_cross_4: { ko: '한 곳에 올인하기보다 비상금을 먼저 쌓고 여유 자금으로 조금씩 분산 투자하는 흐름이 위험을 줄여요. 원금을 지키고 매달 고정 금액 습관을 들이세요.', en: 'Building an emergency fund first, then small diversified investments with spare money, reduces risk; protect principal and build a fixed-amount habit.', ja: '一か所に集中するより緊急資金を先に貯め、余裕資金で少しずつ分散投資する流れがリスクを減らす。元本を守り、毎月一定額の習慣を。' },
  money_2_insight_3: { ko: '겉으로는 방향이 흐릿해 보일 수 있어요. 무리한 투자보다 "안정 저축+소액 분산"이 맞고, 매달 고정 금액을 저축·투자에 쓰는 습관을 들이세요.', en: 'Direction may appear unclear; stable saving and small diversified investment fit you; build a habit of a fixed amount each month.', ja: '表では方向がぼやけて見えるかも。無理な投資より安定貯金＋少額分散が合う。毎月一定額を貯金・投資に回す習慣を。' },

  money_3_time_3: { ko: '지금은 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요. 필요한 것과 원하는 것을 구분하고 매달 지출 한도를 정해 두세요.', en: 'You may feel "small leaks" eating at your finances; separate needs from wants and set a monthly spending limit.', ja: '今は「少しずつ漏れる穴」が財務を削っている感覚かも。必要なものと欲しいものを分け、毎月の支出上限を決めて。' },
  money_3_solution_3: { ko: '스트레스나 권유, "이번만"이라는 생각이 지출을 늘리는 경우가 많아요. 카드 영수증이나 가계부 앱으로 한 달 치를 돌아보면 반복되는 낭비가 보여요.', en: 'Stress, persuasion, or "just this once" often increase spending; a month\'s receipts or budget app will show repeated waste.', ja: 'ストレス・勧め・「今回だけ」が支出を増やすことが多い。カード明細や家計簿アプリで一ヶ月を振り返ると繰り返しの無駄が見える。' },
  money_3_relationship_5: { ko: '지금은 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요. "24시간 rule"을 적용해 보하고, 필요한 것과 원하는 것을 구분해 매달 한도를 정하세요.', en: 'You may feel "small leaks" eating at your finances; try a "24-hour rule" and separate needs from wants with a monthly limit.', ja: '今は「少しずつ漏れる穴」が財務を削っている感覚かも。「24時間ルール」を試し、必要なものと欲しいものを分けて毎月上限を決めて。' },
  money_3_cross_4: { ko: '감정이 올라갔을 때 쇼핑하거나 친구·광고에 이끌려 구매하는 패턴이 있다면 "24시간 rule"을 적용해 보세요. 매달 "쓸 수 있는 한도"를 정해 두세요.', en: 'If you tend to shop when emotional or buy when pushed, try a "24-hour rule"; set a monthly "spending limit."', ja: '感情が高まった時に買い物したり友人・広告に流されて買うパターンがあるなら「24時間ルール」を試して。毎月「使っていい上限」を決めて。' },
  money_3_insight_3: { ko: '겉으로는 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요. 필요한 것과 원하는 것을 구분하고 그 부분부터 줄이면 금전운이 정리되기 시작해요.', en: 'You may feel "small leaks" eating at your finances; separate needs from wants and cutting that first helps your money luck tidy up.', ja: '表では「少しずつ漏れる穴」が財務を削っている感覚かも。必要なものと欲しいものを分け、そこから減らすと金運が整い始める。' },

  relationship_1_time_3: { ko: '주변에서는 당신을 무난하게 좋은 사람, 편한 사람으로 보는 경우가 많아요. "나는 이렇게 생각해", "나는 이런 게 좋아"를 말해 보면 신뢰가 쌓여요.', en: 'People often see you as a nice, easy person; saying "I think this" or "I like that" sometimes builds trust.', ja: '周りはあなたを悪くない良い人・居心地のいい人と見ることが多い。「私はこう思う」「私はこれが好き」と伝えると信頼が積みます。' },
  relationship_1_solution_3: { ko: '"깊이 알아가고 싶다"까지는 아니고 "적당히 친하면 좋겠다" 수준일 수 있어요. 조금 더 본인의 생각이나 감정을 드러내면 관계가 가까워져요.', en: 'They may not be eager to know you deeply; sharing a bit more of your thoughts and feelings brings relationships closer.', ja: '「深く知りたい」まではいかず「程よく仲良くできれば」レベルかも。もう少し自分の考えや感情を出せば関係が近くなる。' },
  relationship_1_relationship_5: { ko: '주변에서는 당신을 무난하게 좋은 사람으로 보지만 속마음을 잘 말하지 않아 "무슨 생각인지 모르겠다"고 느끼는 사람이 있을 수 있어요. 솔직한 한 마디가 신뢰를 키워요.', en: 'People see you as nice but you may not share inner thoughts much, so some feel "I don\'t know what they\'re thinking"; one honest line builds trust.', ja: '周りはあなたを悪くない良い人と見るが、本音をあまり言わないので「何を考えているか分からない」と感じる人も。正直な一言が信頼を育てる。' },
  relationship_1_cross_4: { ko: '"믿을 만한 사람", "일은 잘하는데 감정은 잘 모르겠다" 같은 평가가 섞여 있을 수 있어요. 관계를 깊게 하고 싶다면 생각이나 감정을 조금 더 드러내 보세요.', en: 'Mixed views like "reliable" or "hard to read emotionally" may exist; if you want deeper relationships, share a bit more of your thoughts and feelings.', ja: '「信頼できる人」「仕事はできるが感情は分かりにくい」などの評価が混ざっているかも。関係を深めたいなら考えや感情をもう少し出してみて。' },
  relationship_1_insight_3: { ko: '겉으로는 위협적이지 않고 다가가기 쉬운 이미지지만, 당신을 더 알고 싶어 하는 사람은 당신이 먼저 마음을 열어 주길 기다리고 있을 수 있어요.', en: 'You come across as approachable, not threatening; those who want to know you better may be waiting for you to open up first.', ja: '表では脅威ではなく近づきやすいイメージだが、あなたをもっと知りたい人はあなたが先に心を開くのを待っているかも。' },

  relationship_2_time_3: { ko: '"이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 하나둘 있을 수 있어요. 에너지를 빼앗기만 하거나 맞춰 줘야 하는 관계는 거리를 두세요.', en: 'You may feel "I should keep my distance from this person" in one or two relationships; keep distance from those who only drain you or where you always accommodate.', ja: '「この人とは距離を置いた方がいい」と感じる関係が一二あるかも。エネルギーを奪うだけ・いつも合わせる関係は距離を置いて。' },
  relationship_2_solution_3: { ko: '당신에게 에너지를 빼앗기만 하거나 항상 맞춰 줘야 하는 관계는 거리를 두는 것이 좋아요. "다 좋은 사람이어야 한다"고 생각하지 마세요.', en: 'Keep distance from people who only drain your energy or where you always accommodate; don\'t think "everyone has to be nice."', ja: 'あなたからエネルギーを奪うだけ、いつも合わせる関係は距離を置くのがおすすめ。「みんないい人でなくては」と思わないで。' },
  relationship_2_relationship_5: { ko: '"이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 있을 수 있어요. "내 얘기는 안 물어보고 자기 얘기만", "비난·비교가 많다"는 사람과는 깊이 엮이지 않는 편이 좋아요.', en: 'You may feel "I should keep my distance" in some relationships; with those who "only talk about themselves" or "often blame or compare," it\'s better not to get deeply involved.', ja: '「この人とは距離を置いた方がいい」と感じる関係があるかも。「自分の話ばかりで私の話を聞かない」「批判・比較が多い」人とは深く関わらない方がいい。' },
  relationship_2_cross_4: { ko: '에너지를 빼앗기만 하거나 맞춰 줘야 하는 관계는 거리를 두세요. 부담스러운 요청에는 "지금은 어렵다"고 말해도 되고, 관계는 질이 중요해요.', en: 'Keep distance from those who only drain you or where you always accommodate; it\'s okay to say "I can\'t right now" to burdensome requests—quality matters.', ja: 'エネルギーを奪うだけ・いつも合わせる関係は距離を置いて。負担な頼みには「今は難しい」と言ってよく、関係は質が大事。' },
  relationship_2_insight_3: { ko: '겉으로는 "이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 있어요. "다 좋은 사람이어야 한다"고 생각하지 말고 부담스러운 요청에는 "지금은 어렵다"고 말해도 돼요.', en: 'You may feel "I should keep my distance" in some relationships; don\'t think "everyone has to be nice" and it\'s okay to say "I can\'t right now" to burdensome requests.', ja: '表では「この人とは距離を置いた方がいい」と感じる関係が。「みんないい人でなくては」と思わず、負担な頼みには「今は難しい」と言ってよい。' },

  relationship_3_time_3: { ko: '지금 주변에는 좋은 사람도 있지만 "진짜 내 편"이라고 확신하기 어려운 관계가 섞여 있을 수 있어요. 힘들 때 한 번만 있어 줘도 기억하는 사람이 진짜 친구에 가까워요.', en: 'You have good people around but some relationships may be hard to call "truly on my side"; true friends are often those who are there for you even once when things are hard.', ja: '今の周りには良い人もいるが「本当に味方」と断言しにくい関係が混ざっているかも。辛い時に一度いてくれる人を覚えている人が本当の友達に近い。' },
  relationship_3_solution_3: { ko: '"진짜 내 편"이라고 확신하기 어려운 관계가 있을 수 있어요. 말로만 "응원해"가 아니라 어려울 때 연락이 오거나 작은 도움을 주는 사람을 눈여겨보세요.', en: 'Some relationships may be hard to call "truly on my side"; look for people who reach out or offer small help when you\'re in trouble, not just say "I support you."', ja: '「本当に味方」と断言しにくい関係があるかも。言葉で「応援してる」だけでなく、困った時に連絡が来たり小さな手助けをしてくれる人を目に留めて。' },
  relationship_3_relationship_5: { ko: '수많은 인연보다 힘들 때 한 번만 있어 줘도 기억하는 사람이 진짜 친구에 가까워요. 당신의 말을 경청하고 비난하지 않고 들어 주는 사람이 진짜 친구예요.', en: 'True friends are often those who are there for you even once when things are hard, not the many shallow connections; those who listen without blaming are real friends.', ja: '数多くの縁より、辛い時に一度いてくれる人を覚えている人が本当の友達に近い。あなたの話を傾聴し責めずに聞いてくれる人が本当の友達。' },
  relationship_3_cross_4: { ko: '진짜 내 편은 말로만 "응원해"가 아니라 어려울 때 연락이 오거나 작은 도움을 주는 사람이에요. 일·취미·모임을 통해 "마음이 맞는다"고 느끼는 인연이 생길 수 있어요.', en: 'True allies reach out or offer small help when you\'re in trouble, not just say "I support you"; through work, hobbies, or gatherings you may meet people you feel "in sync with."', ja: '本当の味方は言葉で「応援してる」だけでなく、困った時に連絡が来たり小さな手助けをしてくれる人。仕事・趣味・集まりで「気が合う」と感じる縁ができるかも。' },
  relationship_3_insight_3: { ko: '겉으로는 "진짜 내 편"이라고 확신하기 어려운 관계가 섞여 있어요. 먼저 다가가거나 작은 부탁을 해 보는 것이 관계를 시작하는 데 도움이 되고, 기존 친구에게 마음을 열어 보면 깊어질 수 있어요.', en: 'Some relationships may be hard to call "truly on my side"; making the first move or asking a small favor can start a relationship; opening up to existing friends can deepen it.', ja: '表では「本当に味方」と断言しにくい関係が混ざっている。こちらから近づいたり小さな頼みをしてみると関係が始まり、既存の友達に心を開いてみると深まることが。' },

  fortune_1_time_3: { ko: '지금은 "조금씩 정리되는" 느낌의 시기예요. 중반에 작은 기회나 "덕분에 잘됐다"는 경험이 한두 번 생길 수 있고, 연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.', en: 'A phase of "things settling bit by bit"; in the middle you may have one or two small opportunities or "it went well thanks to that" experiences; toward year-end what you did may feel wrapped up or recognized.', ja: '今は「少しずつ整理される」感覚の時期。中盤に小さなチャンスや「おかげでうまくいった」経験が一二回あるかも。年末に近づくほど今年やったことがまとまったり認められる感覚が。' },
  fortune_1_solution_3: { ko: '마음이나 환경, 인간관계를 가볍게 정리하고 나면 다음 단계로 넘어가기 좋은 토대가 만들어져요. 연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.', en: 'Lightly organizing your mind, environment, and relationships creates a good base for the next step; toward year-end what you did may feel wrapped up or recognized.', ja: '心・環境・人間関係を軽く整理すると次のステップへ移りやすい土台ができる。年末に近づくほど今年やったことがまとまったり認められる感覚が。' },
  fortune_1_relationship_5: { ko: '지금은 "조금씩 정리되는" 느낌의 시기예요. 중반에 작은 기회나 "덕분에 잘됐다"는 경험이 생길 수 있고, 내년을 위한 씨앗을 뿌려 두면 다음 해가 더 풍성해질 수 있어요.', en: 'A phase of "things settling bit by bit"; in the middle you may have small opportunities or "it went well" experiences; sowing seeds for next year can make the coming year richer.', ja: '今は「少しずつ整理される」感覚の時期。中盤に小さなチャンスや「おかげでうまくいった」経験があるかも。来年のための種をまいておくと翌年がより豊かになる。' },
  fortune_1_cross_4: { ko: '급하게 결과를 바라기보다 할 수 있는 일을 착실히 하는 것이 운을 키워요. 중반에 작은 기회가 생길 수 있고, 연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.', en: 'Steady effort builds luck more than hoping for quick results; in the middle you may have small opportunities; toward year-end what you did may feel wrapped up or recognized.', ja: '結果を急がず、できることを着実にすることが運を育てる。中盤に小さなチャンスがあるかも。年末に近づくほど今年やったことがまとまったり認められる感覚が。' },
  fortune_1_insight_3: { ko: '겉으로는 "조금씩 정리되는" 느낌의 시기예요. 중반에 작은 기회나 "덕분에 잘됐다"는 경험이 생길 수 있고, "고생한 보람이 있다"고 느끼는 순간이 오면 작은 축하를 해 주세요.', en: 'A phase of "things settling bit by bit"; in the middle you may have small opportunities; when you feel "it was worth the effort," a small celebration is good.', ja: '表では「少しずつ整理される」感覚の時期。中盤に小さなチャンスや「おかげでうまくいった」経験があるかも。「頑張った甲斐があった」と感じる瞬間が来たら少しお祝いして。' },

  fortune_2_time_3: { ko: '눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요. 기회는 "큰 이벤트"보다 "작은 문이 열리는" 형태로 올 가능성이 많아요.', en: 'Something or someone that feels "this is it" may be approaching; opportunities may come more as "small doors opening" than as big events.', ja: '目立たないが「これだ」と感じる出来事や人が近づいているかも。チャンスは「大きなイベント」より「小さな扉が開く」形で来ることが多い。' },
  fortune_2_solution_3: { ko: '"이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요. "내가 원하는 게 뭔지"를 대략이라도 정해 두면 문이 열렸을 때 들어갈 수 있어요.', en: 'Something that feels "this is it" may be approaching; having a rough idea of "what I want" lets you step in when the door opens.', ja: '「これだ」と感じる出来事や人が近づいているかも。「自分が何を望んでいるか」を大まかで決めておけば扉が開いた時に入れる。' },
  fortune_2_relationship_5: { ko: '지금은 눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요. "이건 기회가 아니야"라고 무시하지 말고 한 번 참여해 보거나 이야기를 들어 보세요.', en: 'Something that feels "this is it" may be approaching; don\'t dismiss as "not an opportunity"—try joining once or listening.', ja: '今は目立たないが「これだ」と感じる出来事や人が近づいているかも。「これはチャンスじゃない」と見送らず、一度参加したり話を聞いてみて。' },
  fortune_2_cross_4: { ko: '일상 속에서 새로 시작한 습관, 우연히 만난 사람, 흘려들은 정보가 나중에 기회로 이어질 수 있어요. "이것만은 해 보자"라고 정한 일을 꾸준히 하면 운이 당신 쪽으로 걸어와요.', en: 'A new habit, someone you met by chance, or information you overheard can later turn into opportunity; doing one thing you\'ve decided "I\'ll at least try this" tends to bring luck your way.', ja: '日常で始めた習慣、偶然会った人、聞き流した情報が後でチャンスにつながることが。「これだけはやってみよう」と決めたことを続けると、運がこちらの方へ歩いてくる。' },
  fortune_2_insight_3: { ko: '겉으로는 눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요. 부담스럽지 않은 범위에서 "이것만은 해 보자"라고 정한 일을 꾸준히 하면 운이 당신 쪽으로 걸어와요.', en: 'Something that feels "this is it" may be approaching; within a comfortable range, doing one thing you\'ve decided "I\'ll at least try this" tends to bring luck your way.', ja: '表では目立たないが「これだ」と感じる出来事や人が近づいているかも。負担のない範囲で「これだけはやってみよう」と決めたことを続けると、運がこちらの方へ歩いてくる。' },

  fortune_3_time_3: { ko: '지금은 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요. 중요한 일은 하루 잠들어 보거나 신뢰하는 사람에게 말해 본 뒤에 결정하세요.', en: 'Fatigue or stress may be building, so judgment can be clouded; sleep on important matters or talk to someone you trust before deciding.', ja: '疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。重要なことは一晩寝かせるか、信頼する人に話してから決めて。' },
  fortune_3_solution_3: { ko: '"오늘만", "이번만"이라는 생각으로 큰 결정을 하면 나중에 후회할 수 있어요. 감정이 올라갔을 때의 결단은 미루고, 건강을 조금만 챙겨도 판단력이 돌아와요.', en: 'Making big decisions with "just today" or "just this once" can lead to regret; postpone big decisions when emotions are high; a little care of health brings back judgment.', ja: '「今日だけ」「今回だけ」の気持ちで大きな決断をすると後悔することが。感情が高まった時の決断は延ばし、健康を少しでも整えると判断力が戻る。' },
  fortune_3_relationship_5: { ko: '지금은 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요. "오늘만", "이번만"이라는 생각으로 큰 결정을 하면 후회할 수 있으니, 중요한 일은 하루 잠들어 보거나 신뢰하는 사람에게 말해 본 뒤에 결정하세요.', en: 'Fatigue or stress may be building; making big decisions with "just today" or "just this once" can lead to regret—sleep on important matters or talk to someone you trust before deciding.', ja: '疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。「今日だけ」「今回だけ」の気持ちで大きな決断をすると後悔することが。重要なことは一晩寝かせるか、信頼する人に話してから決めて。' },
  fortune_3_cross_4: { ko: '감정이 올라갔을 때의 결단(이직, 연애, 큰 지출, 관계 정리 등)은 미루는 것이 좋아요. SNS에서의 과한 비교, 밤늦은 시간의 중요한 대화도 피하면 마음이 편해져요.', en: 'Postpone big decisions when emotions are high; avoiding excessive comparison on social media and important conversations late at night helps peace of mind.', ja: '感情が高まった時の決断（転職・恋愛・大きな支出・関係の整理など）は延ばすのがおすすめ。SNSの過度な比較、夜遅い時間の重要な会話も避けると心が楽に。' },
  fortune_3_insight_3: { ko: '겉으로는 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요. "지금 말하지 않으면 안 된다"는 생각은 대부분 착각이에요. 건강을 조금만 챙겨도 판단력이 돌아와요.', en: 'Fatigue or stress may be building; the feeling "I have to say it now" is often an illusion; a little care of health brings back judgment.', ja: '表では疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。「今言わなきゃ」は多くが錯覚。健康を少しでも整えると判断力が戻る。' },
};

function buildDirectAnswerByQuestionAndSpread() {
  const out = {};
  Q.forEach((qId) => {
    out[qId] = {};
    S.forEach((sId) => {
      const key = `${qId}_${sId}`;
      out[qId][sId] = DIRECT_ANSWER_RAW[key] || { ko: '', en: '', ja: '' };
    });
  });
  return out;
}

/** 75개 고유 추가 통찰 — (questionId_spreadId) → { ko, en, ja } 각 2줄. 75개 전부 서로 다른 문구 */
const ADDITIONAL_INSIGHTS_RAW = {
  love_1_time_3: { ko: ['상대 쪽에도 말하지 못한 후회가 남아 있었을 수 있어요.', '새 인연보다 과거 정리를 먼저 할 때가 유리할 수 있어요.'], en: ['They may have had unspoken regret too.', 'Closing the past before new love tends to work better.'], ja: ['相手側にも言えなかった後悔が残っていたかも。', '新しい縁より過去の整理が先のときが有利かも。'] },
  love_1_solution_3: { ko: ['직접 묻기 어렵다면 먼저 본인이 원하는 바를 정리해 보세요.', '다시 사귀기보다 "그 사람이 나를 제대로 알아봐줬으면" 하는 마음이 더 클 수 있어요.'], en: ['If asking directly is hard, clarify what you want first.', 'The wish to feel acknowledged can outweigh getting back together.'], ja: ['直接聞きづらいなら、先に自分が望むことを整理してみて。', '認められたい気持ちが復縁より大きいことが。'] },
  love_1_relationship_5: { ko: ['그 사람은 과거를 완전히 정리하지 못한 상태일 수 있어요.', '당신이 먼저 연락하지 않으면 그쪽도 쉽게 다가오지 않을 가능성이 큽니다.'], en: ['They may not have fully closed the chapter.', 'If you don\'t reach out first, they\'re unlikely to make the first move easily.'], ja: ['その人は過去を完全に区切れていないかも。', 'あなたから連絡しなければ相手も簡単には動かない可能性が高いです。'] },
  love_1_cross_4: { ko: ['시간이 지나면 감정이 옅어지거나 다시 이야기하고 싶어질 수 있어요.', '못 다한 말이 있다면 편지나 짧은 연락으로 정리해 보세요.'], en: ['Over time their feelings may fade or they may want to talk again.', 'If there are things left unsaid, a letter or short message can help close the loop.'], ja: ['時間が経てば感情が薄まるか、また話したくなるか。', '言えなかったことがあれば手紙や短い連絡で整理してみて。'] },
  love_1_insight_3: { ko: ['밖으로 쿨해 보여도 마음까지 정리됐다고 단정하기 어렵습니다.', '먼저 연락하지 않는다면 그쪽도 쉽게 다가오지 않을 가능성이 큽니다.'], en: ['They may seem cool but it\'s hard to say their heart is fully closed.', 'If you don\'t reach out first, they\'re unlikely to move easily.'], ja: ['表ではクールに見えても心まで整理されたとは言い切れません。', 'あなたから連絡しなければ相手も簡単には動かない可能性が高いです。'] },

  love_2_time_3: { ko: ['두 사람의 만남에 필연이 섞여 있다는 느낌이 읽혀요.', '하루하루 대화와 경험을 쌓는 쪽이 유리해요.'], en: ['Your meeting had a sense of fate.', 'Building conversation and experience day by day is favorable.'], ja: ['二人の出会いに必然が混ざっている感覚が読める。', '日々の会話と経験を積む方が有利です。'] },
  love_2_solution_3: { ko: ['"진짜 맞는 사람일까" 불안은 관계를 소중히 하고 있다는 신호예요.', '함께 걸어가며 만드는 쪽이 단기 결과 재촉보다 유리해요.'], en: ['Anxiety about "is this the one?" can be a sign you care.', 'Building the relationship step by step is more favorable than rushing.'], ja: ['「本当に合う人？」の不安は関係を大切にしている証。', '一緒に歩みながら作る方が短期の結果を急ぐより有利です。'] },
  love_2_relationship_5: { ko: ['그 사람은 당신을 소중히 생각하고 관계를 깊게 하고 싶어 할 수 있어요.', '서로 노력하면 깊어질 가능성이 있어요.'], en: ['They may value you and want to deepen the relationship.', 'It can deepen if you both invest.'], ja: ['その人はあなたを大切に思い、関係を深めたいかも。', '二人が努めれば深まる可能性が。'] },
  love_2_cross_4: { ko: ['관계는 아직 성장 단계이고 만남에 필연이 섞여 있어요.', '결과를 재촉하기보다 대화와 경험을 쌓는 쪽이 유리합니다.'], en: ['The relationship is still growing and your meeting had a sense of fate.', 'Building conversation and experience is more favorable than rushing.'], ja: ['関係はまだ成長段階で、出会いに必然が。', '結果を急ぐより会話と経験を積む方が有利です。'] },
  love_2_insight_3: { ko: ['만남에 필연이 섞여 있다는 느낌이 있어요.', '진짜 인연은 함께 걸어가며 만들어지는 경우가 많아요.'], en: ['There\'s a sense of fate in your meeting.', 'True match is often made by walking together.'], ja: ['出会いに必然が混ざっている感覚が。', '本当の運命の人は一緒に歩みながら作られることが多いです。'] },

  love_3_time_3: { ko: ['끌림과 망설임이 함께 있었던 흐름이에요.', '몇 달 안에 관계 방향이 더 분명해질 가능성이 큽니다.'], en: ['There has been both attraction and hesitation.', 'The direction may become clearer within a few months.'], ja: ['惹かれつつ迷いもあった流れです。', '数ヶ月以内に関係の方向性がはっきりする可能性が高いです。'] },
  love_3_solution_3: { ko: ['"이 관계를 어떻게 할지" 불명확할 수 있어요.', '지금 할 수 있는 말과 행동을 하는 쪽이 후회가 적어요.'], en: ['You may feel unclear about the relationship.', 'Doing what you can say and do now tends to leave fewer regrets.'], ja: ['「この関係をどうするか」不明確かも。', '今できる言葉と行動をすることが後悔を減らします。'] },
  love_3_relationship_5: { ko: ['두 사람 모두 관계를 소중히 생각하지만 확신이 없을 수 있어요.', '솔직히 말하고 들으면 몇 달 안에 방향이 분명해질 수 있어요.'], en: ['You both may value the relationship but lack certainty.', 'Speaking and listening honestly can clarify direction within months.'], ja: ['二人とも関係を大切にしているが確信がないかも。', '正直に話し聞けば数ヶ月で方向がはっきりすることが。'] },
  love_3_cross_4: { ko: ['지금은 전환점이에요. 상대 반응에 일희일비하지 마세요.', '자신이 원하는 방향을 먼저 정리하는 것이 좋아요.'], en: ['You\'re at a turning point; don\'t swing with every reaction.', 'Clarify what you want first.'], ja: ['今は転換点。相手の反応に一喜一憂しないで。', '自分が望む方向を先に整理するのがおすすめです。'] },
  love_3_insight_3: { ko: ['겉으로는 잘 지내는 사이처럼 보여도 고민이 있을 수 있어요.', '할 수 있는 말과 행동을 하는 쪽이 후회가 적어요.'], en: ['On the surface it may look like you get along, but there may be worry.', 'Doing what you can say and do tends to leave fewer regrets.'], ja: ['表では仲良くしているように見えても悩みがあるかも。', 'できる言葉と行動をすることが後悔を減らします。'] },

  career_1_time_3: { ko: ['과거에 불만이 쌓였고 지금은 방향을 정리하는 신호예요.', '반년~1년 안에 기회가 보일 수 있어요.'], en: ['Frustration built in the past; now is a signal to clarify direction.', 'Opportunities may appear within six months to a year.'], ja: ['過去に不満が溜まり、今は方向を整理するサイン。', '半年〜1年以内にチャンスが見えるかも。'] },
  career_1_solution_3: { ko: ['어떤 방향으로 가고 싶은지 먼저 정리하는 것이 유리해요.', '준비가 되어 있을 때 타이밍이 열리는 경우가 많아요.'], en: ['Clarifying which direction you want first is favorable.', 'Timing often opens when you\'re ready.'], ja: ['どの方向へ行きたいか先に整理するのが有利。', '準備が整った時にタイミングが開くことが多いです。'] },
  career_1_relationship_5: { ko: ['성장 욕구와 현실 사이 간격을 느끼고 있을 수 있어요.', '준비가 되어 있을 때 반년~1년 안에 한두 번 기회가 보일 가능성이 있어요.'], en: ['You may feel the gap between your desire to grow and reality.', 'When you\'re ready, one or two opportunities may appear within six months to a year.'], ja: ['成長欲求と現実のギャップを感じているかも。', '準備が整えば半年〜1年以内に一二回チャンスが見える可能性が。'] },
  career_1_cross_4: { ko: ['지금은 방향을 먼저 정리하고 실력·인맥·정보를 쌓아 두세요.', '반년~1년 안에 기회가 보이는 흐름이에요.'], en: ['Clarify direction and build skills, network, and information now.', 'Opportunities may appear within six months to a year.'], ja: ['今は方向を先に整理し、実力・人脈・情報を積んでおいて。', '半年〜1年以内にチャンスが見える流れです。'] },
  career_1_insight_3: { ko: ['겉으로 괜찮아 보여도 "언제쯤 기회가 올까" 생각이 있을 수 있어요.', '그때를 위해 지금 할 수 있는 준비를 해 두세요.'], en: ['You may seem fine but wonder when an opportunity will come.', 'Prepare now for that time.'], ja: ['表では大丈夫に見えても「いつ頃チャンスが来るか」と思っているかも。', 'その時のために今できる準備をしておいて。'] },

  career_2_time_3: { ko: ['과거에 쓸 만한 사람으로 보이기 시작했어요.', '지금은 결과를 보여주는 한두 번의 일이 관계를 바꿀 수 있는 시기예요.'], en: ['They started to see you as useful in the past.', 'Now one or two concrete results can change the relationship.'], ja: ['過去に使える人と見られ始めた。', '今は結果を見せる仕事が一二回あると関係が変わる時期です。'] },
  career_2_solution_3: { ko: ['아직 완전히 믿고 맡기기에는 한 단계 부족하다고 느낄 수 있어요.', '말만 하지 말고 결과를 보여주는 일이 관계를 바꿔요.'], en: ['They may feel one step short of fully trusting you with more.', 'Concrete results can change the relationship.'], ja: ['完全に任せるにはあと一歩と感じているかも。', '言葉より結果を見せる仕事が関係を変えます。'] },
  career_2_relationship_5: { ko: ['상사는 당신을 키워볼 만한 사람으로 보지만 한 단계 부족하다고 느낄 수 있어요.', '결과를 보여주는 한두 번의 일이 관계를 바꿀 수 있어요.'], en: ['Your boss may see you as worth developing but feel one step short.', 'One or two concrete results can change the relationship.'], ja: ['上司はあなたを育てる価値がある人と見ているが、あと一歩と感じているかも。', '結果を見せる仕事が一二回あると関係が変わります。'] },
  career_2_cross_4: { ko: ['팀에서 꼭 필요한 한 명이지만 "이 사람 없이는 안 된다" 수준까지는 아닐 수 있어요.', '꾸준히 신뢰를 쌓으면 몇 달 안에 위치가 올라갈 수 있어요.'], en: ['You\'re one of the necessary people but not yet indispensable.', 'Building trust steadily can raise your standing within months.'], ja: ['チームで必要な一人だが「この人がいないと困る」レベルまではいかないかも。', 'コツコツ信頼を積めば数ヶ月でポジションが上がるかも。'] },
  career_2_insight_3: { ko: ['상사·동료는 아직 "한 단계 더 보여주면 믿고 맡기겠다"는 단계일 수 있어요.', '특정 분야에서 강점을 보이거나 위기에서 한 번 잘 해내면 위치가 올라갈 수 있어요.'], en: ['Your boss and colleagues may still be at "show us one more step."', 'Showing strength in one area or performing well in a pinch can raise your standing.'], ja: ['上司・同僚はまだ「あと一歩見せてくれたら任せたい」段階かも。', '特定分野で強みを見せるか、ピンチで一度結果を出せばポジションが上がるかも。'] },

  career_3_time_3: { ko: ['큰 불행은 없지만 눈에 띄는 행운이 쏟아지는 단계는 아니에요.', '꾸준히 일하면 조금씩 인정받고 작은 기회가 생기는 흐름이에요.'], en: ['No major misfortune but not a phase of obvious windfalls.', 'Steady work tends to bring gradual recognition and small opportunities.'], ja: ['大きな不幸はないが、目立つ幸運が降り注ぐ段階ではない。', 'コツコツ仕事をすれば少しずつ認められ、小さなチャンスが生まれる流れです。'] },
  career_3_solution_3: { ko: ['대박을 노리기보다 할 수 있는 일을 착실히 하는 것이 운을 키워요.', '동료·상사 중 좋은 영향을 주는 사람이 있어요.'], en: ['Doing what you can reliably helps build luck more than chasing a big break.', 'There are people who have a positive influence on you.'], ja: ['大当たりを狙うよりできることを着実にすることが運を育てる。', '同僚・上司の中に良い影響を与える人がいます。'] },
  career_3_relationship_5: { ko: ['일운은 "꾸준히 인정받고 작은 기회가 생기는" 흐름에 가까워요.', '몇 달~1년 사이에 "이번 일 잘됐다" 같은 경험이 한두 번 생길 가능성이 있어요.'], en: ['Your work luck is closer to gradual recognition and small opportunities.', 'Within months to a year you may have one or two "that went well" experiences.'], ja: ['仕事運は「少しずつ認められ、小さなチャンスが生まれる」流れに近い。', '数ヶ月〜1年以内に「この仕事うまくいった」という経験が一二回ある可能性が。'] },
  career_3_cross_4: { ko: ['지금은 꾸준히 일하면 조금씩 인정받고 작은 기회가 생기는 흐름이에요.', '그때를 위해 지금 할 수 있는 준비를 해 두세요.'], en: ['Now steady work tends to bring gradual recognition and small opportunities.', 'Prepare now for that time.'], ja: ['今はコツコツ仕事をすれば少しずつ認められ、小さなチャンスが生まれる流れ。', 'その時のために今できる準備をしておいて。'] },
  career_3_insight_3: { ko: ['겉으로는 평범한 일상처럼 보여도 꾸준히 일하면 인정받고 작은 기회가 생겨요.', '몇 달~1년 사이에 "이번 일 잘됐다" 같은 경험이 생길 수 있어요.'], en: ['On the surface it may look like ordinary routine, but steady work brings recognition and small opportunities.', 'Within months to a year you may have a "that went well" experience.'], ja: ['表では平凡な日常に見えても、コツコツ仕事をすれば認められ小さなチャンスが。', '数ヶ月〜1年以内に「この仕事うまくいった」という経験があるかも。'] },

  money_1_time_3: { ko: ['꾸준한 소득이나 작은 보너스가 이어지는 흐름일 수 있어요.', '반년~1년 안에 수입이 늘거나 예상치 못한 소득이 생길 가능성이 있어요.'], en: ['You may see steady income or small bonuses now.', 'Within six months to a year income may increase or unexpected money may appear.'], ja: ['安定した収入や小さなボーナスが続く流れかも。', '半年〜1年以内に収入が増えたり予想外の収入がある可能性が。'] },
  money_1_solution_3: { ko: ['불필요한 지출을 줄이고 저축·정리를 해 두면 나중에 수월해져요.', '돈이 들어오기 전에 쓰는 습관을 줄이세요.'], en: ['Cutting unnecessary spending and saving or organizing now will make later easier.', 'Reduce the habit of spending before money arrives.'], ja: ['無駄な支出を減らし貯金・整理をしておくと、あとで楽に。', 'お金が入る前に使う癖を減らして。'] },
  money_1_relationship_5: { ko: ['지금은 꾸준한 소득 흐름일 수 있어요.', '정보를 모으고 준비해 둔 자격이나 실력이 있으면 반년~1년 안에 그때 발휘될 수 있어요.'], en: ['You may see steady income now.', 'If you\'ve gathered information and have skills or credentials ready, they can pay off within six months to a year.'], ja: ['今は安定した収入の流れかも。', '情報を集め、資格や実力の準備があれば半年〜1年以内にその時に活きるかも。'] },
  money_1_cross_4: { ko: ['지금은 꾸준한 소득이나 작은 보너스 흐름일 수 있어요.', '돈이 들어오기 전에 쓰는 습관을 줄이고 들어온 돈의 일부는 따로 모아 두세요.'], en: ['You may see steady income or small bonuses now.', 'Reduce spending before money arrives and set aside part of what comes in.'], ja: ['今は安定した収入や小さなボーナスの流れかも。', 'お金が入る前に使う癖を減らし、入ったお金の一部は別に貯めて。'] },
  money_1_insight_3: { ko: ['겉으로는 큰 수입이 한 번에 들어오는 단계는 아닐 수 있어요.', '"나중에"라고 미루지 말고 이번 달부터 작은 금액이라도 저축을 시작하세요.'], en: ['You may not be in a phase of one big windfall.', 'Don\'t put it off "for later"—start saving even a small amount this month.'], ja: ['表では大きな収入が一気に入る段階ではないかも。', '「あとで」と延ばさず、今月から少額でも貯金を始めて。'] },

  money_2_time_3: { ko: ['과거에 "뭔가 해야 할 것 같은데 뭘 해야 할지 모르겠다"는 느낌이 있었을 수 있어요.', '무리한 투자보다 안정 저축+소액 분산이 당신에게 맞아요.'], en: ['You may have felt "I should do something but don\'t know what."', 'Stable saving and small diversified investment tend to fit you better than aggressive investing.'], ja: ['過去に「何かした方がいいけど何をすればいいか分からない」感覚があったかも。', '無理な投資より安定貯金＋少額分散があなたに合います。'] },
  money_2_solution_3: { ko: ['방향이 흐릿할 수 있어요. 유행하는 말에 쉽게 끌려가지 마세요.', '매달 고정 금액을 저축·투자에 쓰는 습관을 들이세요.'], en: ['Direction may feel unclear; don\'t be pulled in by hype.', 'Build a habit of putting a fixed amount into saving/investment each month.'], ja: ['方向がぼやけているかも。流行に簡単に乗らないで。', '毎月一定額を貯金・投資に回す習慣をつけて。'] },
  money_2_relationship_5: { ko: ['지금은 "뭔가 해야 할 것 같은데 뭘 해야 할지 모르겠다"는 방향이 흐릿한 상태일 수 있어요.', '원금을 지키는 것을 최우선으로 하세요.'], en: ['You may feel direction is unclear.', 'Protect principal first.'], ja: ['今は「何かした方がいいけど何をすればいいか分からない」と方向がぼやけているかも。', '元本を守ることを最優先に。'] },
  money_2_cross_4: { ko: ['한 곳에 올인하기보다 비상금을 먼저 쌓고 여유 자금으로 조금씩 분산 투자하세요.', '원금을 지키고 매달 고정 금액 습관을 들이세요.'], en: ['Build an emergency fund first, then small diversified investments with spare money.', 'Protect principal and build a fixed-amount habit.'], ja: ['一か所に集中するより緊急資金を先に貯め、余裕資金で少しずつ分散投資して。', '元本を守り、毎月一定額の習慣を。'] },
  money_2_insight_3: { ko: ['겉으로는 방향이 흐릿해 보일 수 있어요.', '무리한 투자보다 "안정 저축+소액 분산"이 맞고, 매달 고정 금액 습관을 들이세요.'], en: ['Direction may appear unclear.', 'Stable saving and small diversified investment fit you; build a habit of a fixed amount each month.'], ja: ['表では方向がぼやけて見えるかも。', '無理な投資より安定貯金＋少額分散が合う。毎月一定額を貯金・投資に回す習慣を。'] },

  money_3_time_3: { ko: ['지금은 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요.', '필요한 것과 원하는 것을 구분하고 매달 지출 한도를 정해 두세요.'], en: ['You may feel "small leaks" eating at your finances.', 'Separate needs from wants and set a monthly spending limit.'], ja: ['今は「少しずつ漏れる穴」が財務を削っている感覚かも。', '必要なものと欲しいものを分け、毎月の支出上限を決めて。'] },
  money_3_solution_3: { ko: ['스트레스나 권유, "이번만"이라는 생각이 지출을 늘리는 경우가 많아요.', '한 달 치 영수증이나 가계부 앱으로 돌아보면 반복되는 낭비가 보여요.'], en: ['Stress, persuasion, or "just this once" often increase spending.', 'A month\'s receipts or budget app will show repeated waste.'], ja: ['ストレス・勧め・「今回だけ」が支出を増やすことが多い。', '一ヶ月分の明細や家計簿アプリで振り返ると繰り返しの無駄が見える。'] },
  money_3_relationship_5: { ko: ['지금은 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요.', '"24시간 rule"을 적용해 보하고, 필요한 것과 원하는 것을 구분해 매달 한도를 정하세요.'], en: ['You may feel "small leaks" eating at your finances.', 'Try a "24-hour rule" and separate needs from wants with a monthly limit.'], ja: ['今は「少しずつ漏れる穴」が財務を削っている感覚かも。', '「24時間ルール」を試し、必要なものと欲しいものを分けて毎月上限を決めて。'] },
  money_3_cross_4: { ko: ['감정이 올라갔을 때 쇼핑하거나 친구·광고에 이끌려 구매하는 패턴이 있다면 "24시간 rule"을 적용해 보세요.', '매달 "쓸 수 있는 한도"를 정해 두세요.'], en: ['If you tend to shop when emotional or buy when pushed, try a "24-hour rule."', 'Set a monthly "spending limit."'], ja: ['感情が高まった時に買い物したり友人・広告に流されて買うパターンがあるなら「24時間ルール」を試して。', '毎月「使っていい上限」を決めて。'] },
  money_3_insight_3: { ko: ['겉으로는 "조금씩 새는 구멍"이 재정을 갉아먹는 느낌일 수 있어요.', '필요한 것과 원하는 것을 구분하고 그 부분부터 줄이면 금전운이 정리되기 시작해요.'], en: ['You may feel "small leaks" eating at your finances.', 'Separate needs from wants and cutting that first helps your money luck tidy up.'], ja: ['表では「少しずつ漏れる穴」が財務を削っている感覚かも。', '必要なものと欲しいものを分け、そこから減らすと金運が整い始める。'] },

  relationship_1_time_3: { ko: ['주변에서는 당신을 무난하게 좋은 사람, 편한 사람으로 보는 경우가 많아요.', '"나는 이렇게 생각해", "나는 이런 게 좋아"를 말해 보면 신뢰가 쌓여요.'], en: ['People often see you as a nice, easy person.', 'Saying "I think this" or "I like that" sometimes builds trust.'], ja: ['周りはあなたを悪くない良い人・居心地のいい人と見ることが多い。', '「私はこう思う」「私はこれが好き」と伝えると信頼が積みます。'] },
  relationship_1_solution_3: { ko: ['"깊이 알아가고 싶다"까지는 아니고 "적당히 친하면 좋겠다" 수준일 수 있어요.', '조금 더 본인의 생각이나 감정을 드러내면 관계가 가까워져요.'], en: ['They may not be eager to know you deeply.', 'Sharing a bit more of your thoughts and feelings brings relationships closer.'], ja: ['「深く知りたい」まではいかず「程よく仲良くできれば」レベルかも。', 'もう少し自分の考えや感情を出せば関係が近くなる。'] },
  relationship_1_relationship_5: { ko: ['주변에서는 당신을 무난하게 좋은 사람으로 보지만 속마음을 잘 말하지 않아 "무슨 생각인지 모르겠다"고 느끼는 사람이 있을 수 있어요.', '솔직한 한 마디가 신뢰를 키워요.'], en: ['People see you as nice but you may not share inner thoughts much.', 'One honest line builds trust.'], ja: ['周りはあなたを悪くない良い人と見るが、本音をあまり言わないので「何を考えているか分からない」と感じる人も。', '正直な一言が信頼を育てる。'] },
  relationship_1_cross_4: { ko: ['"믿을 만한 사람", "일은 잘하는데 감정은 잘 모르겠다" 같은 평가가 섞여 있을 수 있어요.', '관계를 깊게 하고 싶다면 생각이나 감정을 조금 더 드러내 보세요.'], en: ['Mixed views like "reliable" or "hard to read emotionally" may exist.', 'If you want deeper relationships, share a bit more of your thoughts and feelings.'], ja: ['「信頼できる人」「仕事はできるが感情は分かりにくい」などの評価が混ざっているかも。', '関係を深めたいなら考えや感情をもう少し出してみて。'] },
  relationship_1_insight_3: { ko: ['겉으로는 위협적이지 않고 다가가기 쉬운 이미지예요.', '당신을 더 알고 싶어 하는 사람은 당신이 먼저 마음을 열어 주길 기다리고 있을 수 있어요.'], en: ['You come across as approachable, not threatening.', 'Those who want to know you better may be waiting for you to open up first.'], ja: ['表では脅威ではなく近づきやすいイメージ。', 'あなたをもっと知りたい人はあなたが先に心を開くのを待っているかも。'] },

  relationship_2_time_3: { ko: ['"이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 하나둘 있을 수 있어요.', '에너지를 빼앗기만 하거나 맞춰 줘야 하는 관계는 거리를 두세요.'], en: ['You may feel "I should keep my distance from this person" in one or two relationships.', 'Keep distance from those who only drain you or where you always accommodate.'], ja: ['「この人とは距離を置いた方がいい」と感じる関係が一二あるかも。', 'エネルギーを奪うだけ・いつも合わせる関係は距離を置いて。'] },
  relationship_2_solution_3: { ko: ['당신에게 에너지를 빼앗기만 하거나 항상 맞춰 줘야 하는 관계는 거리를 두는 것이 좋아요.', '"다 좋은 사람이어야 한다"고 생각하지 마세요.'], en: ['Keep distance from people who only drain your energy or where you always accommodate.', 'Don\'t think "everyone has to be nice."'], ja: ['あなたからエネルギーを奪うだけ、いつも合わせる関係は距離を置くのがおすすめ。', '「みんないい人でなくては」と思わないで。'] },
  relationship_2_relationship_5: { ko: ['"이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 있을 수 있어요.', '"내 얘기는 안 물어보고 자기 얘기만", "비난·비교가 많다"는 사람과는 깊이 엮이지 않는 편이 좋아요.'], en: ['You may feel "I should keep my distance" in some relationships.', 'With those who "only talk about themselves" or "often blame or compare," it\'s better not to get deeply involved.'], ja: ['「この人とは距離を置いた方がいい」と感じる関係があるかも。', '「自分の話ばかりで私の話を聞かない」「批判・比較が多い」人とは深く関わらない方がいい。'] },
  relationship_2_cross_4: { ko: ['에너지를 빼앗기만 하거나 맞춰 줘야 하는 관계는 거리를 두세요.', '부담스러운 요청에는 "지금은 어렵다"고 말해도 되고, 관계는 질이 중요해요.'], en: ['Keep distance from those who only drain you or where you always accommodate.', 'It\'s okay to say "I can\'t right now" to burdensome requests—quality matters.'], ja: ['エネルギーを奪うだけ・いつも合わせる関係は距離を置いて。', '負担な頼みには「今は難しい」と言ってよく、関係は質が大事。'] },
  relationship_2_insight_3: { ko: ['겉으로는 "이 사람이랑은 거리두는 게 나을 것 같다"고 느끼는 관계가 있어요.', '"다 좋은 사람이어야 한다"고 생각하지 말고 부담스러운 요청에는 "지금은 어렵다"고 말해도 돼요.'], en: ['You may feel "I should keep my distance" in some relationships.', 'Don\'t think "everyone has to be nice" and it\'s okay to say "I can\'t right now" to burdensome requests.'], ja: ['表では「この人とは距離を置いた方がいい」と感じる関係が。', '「みんないい人でなくては」と思わず、負担な頼みには「今は難しい」と言ってよい。'] },

  relationship_3_time_3: { ko: ['지금 주변에는 좋은 사람도 있지만 "진짜 내 편"이라고 확신하기 어려운 관계가 섞여 있을 수 있어요.', '힘들 때 한 번만 있어 줘도 기억하는 사람이 진짜 친구에 가까워요.'], en: ['You have good people around but some relationships may be hard to call "truly on my side."', 'True friends are often those who are there for you even once when things are hard.'], ja: ['今の周りには良い人もいるが「本当に味方」と断言しにくい関係が混ざっているかも。', '辛い時に一度いてくれる人を覚えている人が本当の友達に近い。'] },
  relationship_3_solution_3: { ko: ['"진짜 내 편"이라고 확신하기 어려운 관계가 있을 수 있어요.', '말로만 "응원해"가 아니라 어려울 때 연락이 오거나 작은 도움을 주는 사람을 눈여겨보세요.'], en: ['Some relationships may be hard to call "truly on my side."', 'Look for people who reach out or offer small help when you\'re in trouble, not just say "I support you."'], ja: ['「本当に味方」と断言しにくい関係があるかも。', '言葉で「応援してる」だけでなく、困った時に連絡が来たり小さな手助けをしてくれる人を目に留めて。'] },
  relationship_3_relationship_5: { ko: ['수많은 인연보다 힘들 때 한 번만 있어 줘도 기억하는 사람이 진짜 친구에 가까워요.', '당신의 말을 경청하고 비난하지 않고 들어 주는 사람이 진짜 친구예요.'], en: ['True friends are often those who are there for you even once when things are hard.', 'Those who listen without blaming are real friends.'], ja: ['数多くの縁より、辛い時に一度いてくれる人を覚えている人が本当の友達に近い。', 'あなたの話を傾聴し責めずに聞いてくれる人が本当の友達。'] },
  relationship_3_cross_4: { ko: ['진짜 내 편은 말로만 "응원해"가 아니라 어려울 때 연락이 오거나 작은 도움을 주는 사람이에요.', '일·취미·모임을 통해 "마음이 맞는다"고 느끼는 인연이 생길 수 있어요.'], en: ['True allies reach out or offer small help when you\'re in trouble, not just say "I support you."', 'Through work, hobbies, or gatherings you may meet people you feel "in sync with."'], ja: ['本当の味方は言葉で「応援してる」だけでなく、困った時に連絡が来たり小さな手助けをしてくれる人。', '仕事・趣味・集まりで「気が合う」と感じる縁ができるかも。'] },
  relationship_3_insight_3: { ko: ['겉으로는 "진짜 내 편"이라고 확신하기 어려운 관계가 섞여 있어요.', '먼저 다가가거나 작은 부탁을 해 보는 것이 관계를 시작하는 데 도움이 되고, 기존 친구에게 마음을 열어 보면 깊어질 수 있어요.'], en: ['Some relationships may be hard to call "truly on my side."', 'Making the first move or asking a small favor can start a relationship; opening up to existing friends can deepen it.'], ja: ['表では「本当に味方」と断言しにくい関係が混ざっている。', 'こちらから近づいたり小さな頼みをしてみると関係が始まり、既存の友達に心を開いてみると深まることが。'] },

  fortune_1_time_3: { ko: ['지금은 "조금씩 정리되는" 느낌의 시기예요.', '중반에 작은 기회나 "덕분에 잘됐다"는 경험이 한두 번 생길 수 있고, 연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.'], en: ['A phase of "things settling bit by bit."', 'In the middle you may have one or two small opportunities; toward year-end what you did may feel wrapped up or recognized.'], ja: ['今は「少しずつ整理される」感覚の時期。', '中盤に小さなチャンスや「おかげでうまくいった」経験が一二回あるかも。年末に近づくほど今年やったことがまとまったり認められる感覚が。'] },
  fortune_1_solution_3: { ko: ['마음이나 환경, 인간관계를 가볍게 정리하고 나면 다음 단계로 넘어가기 좋은 토대가 만들어져요.', '연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.'], en: ['Lightly organizing your mind, environment, and relationships creates a good base for the next step.', 'Toward year-end what you did may feel wrapped up or recognized.'], ja: ['心・環境・人間関係を軽く整理すると次のステップへ移りやすい土台ができる。', '年末に近づくほど今年やったことがまとまったり認められる感覚が。'] },
  fortune_1_relationship_5: { ko: ['지금은 "조금씩 정리되는" 느낌의 시기예요.', '중반에 작은 기회나 "덕분에 잘됐다"는 경험이 생길 수 있고, 내년을 위한 씨앗을 뿌려 두면 다음 해가 더 풍성해질 수 있어요.'], en: ['A phase of "things settling bit by bit."', 'In the middle you may have small opportunities; sowing seeds for next year can make the coming year richer.'], ja: ['今は「少しずつ整理される」感覚の時期。', '中盤に小さなチャンスや「おかげでうまくいった」経験があるかも。来年のための種をまいておくと翌年がより豊かになる。'] },
  fortune_1_cross_4: { ko: ['급하게 결과를 바라기보다 할 수 있는 일을 착실히 하는 것이 운을 키워요.', '중반에 작은 기회가 생길 수 있고, 연말에 가까워질수록 올해 한 일이 정리되거나 인정받는 느낌이 들 수 있어요.'], en: ['Steady effort builds luck more than hoping for quick results.', 'In the middle you may have small opportunities; toward year-end what you did may feel wrapped up or recognized.'], ja: ['結果を急がず、できることを着実にすることが運を育てる。', '中盤に小さなチャンスがあるかも。年末に近づくほど今年やったことがまとまったり認められる感覚が。'] },
  fortune_1_insight_3: { ko: ['겉으로는 "조금씩 정리되는" 느낌의 시기예요.', '중반에 작은 기회나 "덕분에 잘됐다"는 경험이 생길 수 있고, "고생한 보람이 있다"고 느끼는 순간이 오면 작은 축하를 해 주세요.'], en: ['A phase of "things settling bit by bit."', 'In the middle you may have small opportunities; when you feel "it was worth the effort," a small celebration is good.'], ja: ['表では「少しずつ整理される」感覚の時期。', '中盤に小さなチャンスや「おかげでうまくいった」経験があるかも。「頑張った甲斐があった」と感じる瞬間が来たら少しお祝いして。'] },

  fortune_2_time_3: { ko: ['눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요.', '기회는 "큰 이벤트"보다 "작은 문이 열리는" 형태로 올 가능성이 많아요.'], en: ['Something or someone that feels "this is it" may be approaching.', 'Opportunities may come more as "small doors opening" than as big events.'], ja: ['目立たないが「これだ」と感じる出来事や人が近づいているかも。', 'チャンスは「大きなイベント」より「小さな扉が開く」形で来ることが多い。'] },
  fortune_2_solution_3: { ko: ['"이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요.', '"내가 원하는 게 뭔지"를 대략이라도 정해 두면 문이 열렸을 때 들어갈 수 있어요.'], en: ['Something that feels "this is it" may be approaching.', 'Having a rough idea of "what I want" lets you step in when the door opens.'], ja: ['「これだ」と感じる出来事や人が近づいているかも。', '「自分が何を望んでいるか」を大まかで決めておけば扉が開いた時に入れる。'] },
  fortune_2_relationship_5: { ko: ['지금은 눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요.', '"이건 기회가 아니야"라고 무시하지 말고 한 번 참여해 보거나 이야기를 들어 보세요.'], en: ['Something that feels "this is it" may be approaching.', 'Don\'t dismiss as "not an opportunity"—try joining once or listening.'], ja: ['今は目立たないが「これだ」と感じる出来事나人が近づいているかも。', '「これはチャンスじゃない」と見送らず、一度参加したり話を聞いてみて。'] },
  fortune_2_cross_4: { ko: ['일상 속에서 새로 시작한 습관, 우연히 만난 사람, 흘려들은 정보가 나중에 기회로 이어질 수 있어요.', '"이것만은 해 보자"라고 정한 일을 꾸준히 하면 운이 당신 쪽으로 걸어와요.'], en: ['A new habit, someone you met by chance, or information you overheard can later turn into opportunity.', 'Doing one thing you\'ve decided "I\'ll at least try this" tends to bring luck your way.'], ja: ['日常で始めた習慣、偶然会った人、聞き流した情報が後でチャンスにつながることが。', '「これだけはやってみよう」と決めたことを続けると、運がこちらの方へ歩いてくる。'] },
  fortune_2_insight_3: { ko: ['겉으로는 눈에 띄지 않지만 "이거다"라고 느끼는 일이나 사람이 다가오고 있을 수 있어요.', '부담스럽지 않은 범위에서 "이것만은 해 보자"라고 정한 일을 꾸준히 하면 운이 당신 쪽으로 걸어와요.'], en: ['Something that feels "this is it" may be approaching.', 'Within a comfortable range, doing one thing you\'ve decided "I\'ll at least try this" tends to bring luck your way.'], ja: ['表では目立たないが「これだ」と感じる出来事や人が近づいているかも。', '負担のない範囲で「これだけはやってみよう」と決めたことを続けると、運がこちらの方へ歩いてくる。'] },

  fortune_3_time_3: { ko: ['지금은 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요.', '중요한 일은 하루 잠들어 보거나 신뢰하는 사람에게 말해 본 뒤에 결정하세요.'], en: ['Fatigue or stress may be building, so judgment can be clouded.', 'Sleep on important matters or talk to someone you trust before deciding.'], ja: ['疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。', '重要なことは一晩寝かせるか、信頼する人に話してから決めて。'] },
  fortune_3_solution_3: { ko: ['"오늘만", "이번만"이라는 생각으로 큰 결정을 하면 나중에 후회할 수 있어요.', '감정이 올라갔을 때의 결단은 미루고, 건강을 조금만 챙겨도 판단력이 돌아와요.'], en: ['Making big decisions with "just today" or "just this once" can lead to regret.', 'Postpone big decisions when emotions are high; a little care of health brings back judgment.'], ja: ['「今日だけ」「今回だけ」の気持ちで大きな決断をすると後悔することが。', '感情が高まった時の決断は延ばし、健康を少しでも整えると判断力が戻る。'] },
  fortune_3_relationship_5: { ko: ['지금은 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요.', '"오늘만", "이번만"이라는 생각으로 큰 결정을 하면 후회할 수 있으니, 중요한 일은 하루 잠들어 보거나 신뢰하는 사람에게 말해 본 뒤에 결정하세요.'], en: ['Fatigue or stress may be building.', 'Making big decisions with "just today" or "just this once" can lead to regret—sleep on important matters or talk to someone you trust before deciding.'], ja: ['疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。', '「今日だけ」「今回だけ」の気持ちで大きな決断をすると後悔することが。重要なことは一晩寝かせるか、信頼する人に話してから決めて。'] },
  fortune_3_cross_4: { ko: ['감정이 올라갔을 때의 결단(이직, 연애, 큰 지출, 관계 정리 등)은 미루는 것이 좋아요.', 'SNS에서의 과한 비교, 밤늦은 시간의 중요한 대화도 피하면 마음이 편해져요.'], en: ['Postpone big decisions when emotions are high.', 'Avoiding excessive comparison on social media and important conversations late at night helps peace of mind.'], ja: ['感情が高まった時の決断（転職・恋愛・大きな支出・関係の整理など）は延ばすのがおすすめ。', 'SNSの過度な比較、夜遅い時間の重要な会話も避けると心が楽に。'] },
  fortune_3_insight_3: { ko: ['겉으로는 피로나 스트레스가 쌓여 판단이 흐려지거나 감정에 휩쓸리기 쉬운 때일 수 있어요.', '"지금 말하지 않으면 안 된다"는 생각은 대부분 착각이에요. 건강을 조금만 챙겨도 판단력이 돌아와요.'], en: ['Fatigue or stress may be building.', 'The feeling "I have to say it now" is often an illusion; a little care of health brings back judgment.'], ja: ['表では疲れやストレスが溜まり、判断が鈍ったり感情に流されやすい時期かも。', '「今言わなきゃ」は多くが錯覚。健康を少しでも整えると判断力が戻る。'] },
};

function buildAdditionalInsightsByQuestionAndSpread() {
  const out = {};
  Q.forEach((qId) => {
    out[qId] = {};
    S.forEach((sId) => {
      const key = `${qId}_${sId}`;
      const raw = ADDITIONAL_INSIGHTS_RAW[key];
      out[qId][sId] = raw || { ko: ['', ''], en: ['', ''], ja: ['', ''] };
    });
  });
  return out;
}

export const DIRECT_ANSWER_BY_QUESTION_AND_SPREAD = buildDirectAnswerByQuestionAndSpread();
export const ADDITIONAL_INSIGHTS_BY_QUESTION_AND_SPREAD = buildAdditionalInsightsByQuestionAndSpread();
